// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwzfjfxtblvtehdorrpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3emZqZnh0Ymx2dGVoZG9ycnB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjc4MDYsImV4cCI6MjA2NzY0MzgwNn0.TBKH21KvpW3KtkrURAxwfjKH6NazqOUSsoNsG07O3kM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});